name: Release a stable version

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Newest PDF
        run: wget "https://github.com/DanilJeston/DDLC-Chinese-Modding-Guide/raw/master/DDLC Mod 开发指南.pdf"
      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: "DDLC Mod 开发指南.pdf"
          body_path: CHANGELOG.md
